version: '3'

services:
    brevets:
        build: brevets/.
        ports: 
          - "5001:5000"
        depends_on:
          - mongo
        # Borrowed this from your Docker Mongo repo. Needed a predictable hostname.
        environment:
          MONGODB_HOSTNAME: 'mongo'
    mongo:
      image: mongo:5.0.5
      ports:
        - 27017:27017
